[package]
name = "const-primes"
authors = ["Johanna Sörngård <jsorngard@gmail.com>"]
version = "0.8.0"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["const", "primes"]
categories = ["mathematics", "no-std", "no-std::no-alloc", "algorithms"]
description = "Work with prime numbers in const contexts. Prime generation, primality testing, prime counting, factorization, and more."
repository = "https://github.com/JSorngard/const-primes/tree/main"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
rand = "0.8"

[features]
std = []

# docs.rs-specific configuration. Taken from <https://stackoverflow.com/a/61417700/>.
[package.metadata.docs.rs]
# Document all features.
all-features = true
# Enable the docsrs configuration attribute on docs.rs
rustdoc-args = ["--cfg", "docsrs"]

[[bench]]
name = "prime_benches"
harness = false
