[package]
name = "const-primes"
authors = ["Johanna Sörngård (jsorngard@gmail.com)"]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Generate prime numbers at compile time"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
