[package]
name = "const-primes"
authors = ["Johanna Sörngård (jsorngard@gmail.com)"]
version = "0.3.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Generate prime numbers at compile time"
repository = "https://github.com/JSorngard/const-primes"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
criterion = {version = "0.5", features = ["html_reports"]}

[[bench]]
name = "prime_benches"
harness = false