[package]
name = "const-primes"
authors = ["Johanna Sörngård (jsorngard@gmail.com)"]
version = "0.6.1"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["primes", "const"]
categories = ["mathematics", "no-std::no-alloc"]
description = "Generate and work with prime numbers in const contexts"
repository = "https://github.com/JSorngard/const-primes"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
rand = "0.8"

[features]
std = []

# docs.rs-specific configuration. Taken from <https://stackoverflow.com/a/61417700/>.
[package.metadata.docs.rs]
# Document all features.
all-features = true

[[bench]]
name = "prime_benches"
harness = false
